"use client";

import { AreaChart, Area, XAxis, YAxis, ResponsiveContainer, Tooltip } from "recharts";
import Link from "next/link";

const data = [
  { time: "21:00", energy: 100, cumulative: 100 },
  { time: "22:00", energy: 120, cumulative: 120 },
  { time: "23:00", energy: 140, cumulative: 140 },
  { time: "00:00", energy: 110, cumulative: 150 },
  { time: "01:00", energy: 100, cumulative: 140 },
  { time: "02:00", energy: 90, cumulative: 130 },
  { time: "03:00", energy: 70, cumulative: 110 },
  { time: "04:00", energy: 50, cumulative: 110 },
];

export default function EnergyMetrics() {
  return (
    <div className="min-h-screen bg-black flex flex-col items-center justify-center px-4 py-8 md:py-16">
      {/* Header */}
      <div className="text-center mb-8 md:mb-12">
        <h1 className="text-3xl md:text-4xl lg:text-5xl font-serif text-white mb-2">
          ENERGY METRICS
        </h1>
        <p className="text-sm md:text-base text-gray-400">
          Night of the Century Monitoring System
        </p>
      </div>

      {/* KPI Boxes */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6 w-full max-w-6xl mb-8 md:mb-12">
        <div className="bg-gray-900 border-2 border-orange-500 rounded-lg p-6 md:p-8">
          <p className="text-gray-400 text-sm md:text-base mb-2 uppercase tracking-wider">PEAK BPM</p>
          <p className="text-4xl md:text-5xl lg:text-6xl font-bold text-red-500">145</p>
        </div>
        <div className="bg-gray-900 border-2 border-orange-500 rounded-lg p-6 md:p-8">
          <p className="text-gray-400 text-sm md:text-base mb-2 uppercase tracking-wider">RUM CAPACITY</p>
          <p className="text-4xl md:text-5xl lg:text-6xl font-bold text-yellow-400">MAX</p>
        </div>
      </div>

      {/* Chart */}
      <div className="w-full max-w-6xl bg-gray-900 rounded-xl border-2 border-orange-500 border-glow-orange p-4 md:p-6 lg:p-8">
        <ResponsiveContainer width="100%" height={400}>
          <AreaChart data={data}>
            <defs>
              <linearGradient id="colorEnergy" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor="#FFD700" stopOpacity={0.8}/>
                <stop offset="95%" stopColor="#FFD700" stopOpacity={0}/>
              </linearGradient>
              <linearGradient id="colorCumulative" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor="#FF6B35" stopOpacity={0.8}/>
                <stop offset="95%" stopColor="#FF6B35" stopOpacity={0}/>
              </linearGradient>
            </defs>
            <XAxis 
              dataKey="time" 
              stroke="#888888"
              tick={{ fill: '#888888', fontSize: 12 }}
            />
            <YAxis 
              stroke="#888888"
              tick={{ fill: '#888888', fontSize: 12 }}
              domain={[0, 160]}
              ticks={[0, 40, 80, 120, 160]}
            />
            <Tooltip 
              contentStyle={{ 
                backgroundColor: '#1a1a1a', 
                border: '1px solid #ff8c00',
                borderRadius: '8px',
                color: '#fff'
              }}
            />
            <Area 
              type="monotone" 
              dataKey="energy" 
              stroke="#FFD700" 
              fillOpacity={1} 
              fill="url(#colorEnergy)" 
            />
            <Area 
              type="monotone" 
              dataKey="cumulative" 
              stroke="#FF6B35" 
              fillOpacity={1} 
              fill="url(#colorCumulative)" 
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      {/* Footer Disclaimer */}
      <p className="mt-6 md:mt-8 text-xs md:text-sm text-gray-500 text-center max-w-2xl">
        *Data generated by real-time party sensors at Takács HQ
      </p>

      {/* Navigation */}
      <div className="mt-8 md:mt-12">
        <Link 
          href="/"
          className="text-yellow-400 hover:text-yellow-300 text-sm md:text-base transition-colors"
        >
          ← Back to Home
        </Link>
      </div>
    </div>
  );
}

